# Generated by Django 4.0.5 on 2022-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=250)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
